branch-defaults:
  master:
    environment: yclub-services-payment-kr-dev
    group_suffix: null
global:
  application_name: yclub-services-payment-kr
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
